services:
  back:
    build:
      context: docker/${ENV}/back/
      dockerfile: Dockerfile
    ports: 
      - ${API_PORT}:${API_PORT}
    environment:
      - ADYEN_MARKETPLACE_API_KEY=${ADYEN_MARKETPLACE_API_KEY}
      - PORT=${API_PORT}
    volumes:
      - ./apps/back:/usr/src/apps/back
  
  front:
    build:
      context: docker/${ENV}/front
      dockerfile: Dockerfile
    ports: 
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./apps/front:/usr/src/apps/front